[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.54.0", features = ["Win32_Foundation", "Win32_Security_Authentication", "Win32_Security_Authorization", "Win32_Storage_FileSystem"] }