[env.release]
TARGET_PATH = "../target/x86_64-pc-windows-msvc/debug"

[env.development]
TARGET_PATH = "../target/x86_64-pc-windows-msvc/release"
BUILD_RELEASE = "--release"

[env]
VC_BUILD_DIR = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"


[tasks.buildre-driver]
script = '''
cargo b --release %BUILD_FLAGS%
'''

[tasks.build-driver]
script = '''
cargo b --release %BUILD_FLAGS%
'''

[tasks.sign]
dependencies = ["build-driver", "rename"]
script = '''
call "%VC_BUILD_DIR%"
if not exist DriverCertificate.cer ( makecert -r -pe -ss PrivateCertStore -n CN=DriverCertificate DriverCertificate.cer ) else ( echo Certificate already exists. )
"signtool" sign /a /v /s PrivateCertStore /n DriverCertificate /fd certHash /t http://timestamp.digicert.com %TARGET_PATH%/driver.sys
'''

[tasks.rename]
ignore_errors = true
script = '''
cd %TARGET_PATH%
rename driver.dll driver.sys
'''

[tasks.signre]
dependencies = ["buildre-driver", "rename"]
script = '''
call "%VC_BUILD_DIR%"
if not exist DriverCertificate.cer ( makecert -r -pe -ss PrivateCertStore -n CN=DriverCertificate DriverCertificate.cer ) else ( echo Certificate already exists. )
"signtool" sign /a /v /s PrivateCertStore /n DriverCertificate /fd certHash /t http://timestamp.digicert.com %TARGET_PATH%/driver.sys
'''


#sc create example binPath=C:\Users\carlos\driver\driver\driver\target\x86_64-pc-windows-msvc\debug\driver.sys type=kernel
